#pragma config(Sensor, dgtl4,  buttonMain,     sensorDigitalIn)
#pragma config(Sensor, dgtl11, buttonReverse,  sensorDigitalIn)
#pragma config(Motor,  port2,           upperMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
/	Vex Robotics RobotC Program, Test Code 007
/	"Milestone 1: Mechanical Test"
/
/	Paisley Kerstens, Aleksia Loewen, Arfaz Hussain
/
*/

int motorSpeed = 15;                                 // (UNIT) centimeter, cm
int timeConstant = 1500;

void objectPlacement() {
    /*MAIN*/
    motor[upperMotor] = motorSpeed;
    wait1Msec(timeConstant);
}

void objectPlacementReverse() {
    /*MAIN*/
    motor[upperMotor] = -motorSpeed;
    wait1Msec(timeConstant);
}

task main () {
    while (1==1) {                                    // continuity clause
        if (SensorValue[buttonMain] == 0) {               // should be 1 when button is pressed according to documentation
            objectPlacement();                        // function, run - wait - run - stop
		    }
		    else if (SensorValue[buttonReverse] == 0) {
		        objectPlacementReverse();
		    }
        else {                                        // default mode
            motor[upperMotor] = 0;
        }
    }
}
