#pragma config(Sensor, in1, IROut, sensorReflection)
#pragma config(Sensor, dgtl1, yMin, sensorTouch)
#pragma config(Sensor, dgtl2, yMax, sensorTouch)
#pragma config(Sensor, dgtl3, xMin, sensorTouch)
#pragma config(Sensor, dgtl4, xMax, sensorTouch)
#pragma config(Sensor, dgtl6, Red1, sensorLEDtoVCC)
#pragma config(Sensor, dgtl7, Red2, sensorLEDtoVCC)
#pragma config(Sensor, dgtl8, Red3, sensorLEDtoVCC)
#pragma config(Sensor, dgtl9, Red4, sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, Red5, sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, Red, sensorLEDtoVCC)
#pragma config(Motor, port2, xMotor,tmotorServoContinuousRotation, openLoop)
#pragma config(Motor, port3, yMotor,tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard!!*//
int results(int squares);
void moveRight();
void moveLeft();
void moveUp();
void moveDown();
void startPos();
void startPos2();
void scanSameSurface(int num);
int turnVar = 0;
int threshold = 2300;
int squares = 0;
int speed = 125;
int array[15] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
task main()
{
    // startPos2();
    SensorValue[Red] = 0;
    SensorValue[Red1] = 0;
    SensorValue[Red2] = 0;
    SensorValue[Red3] = 0;
    SensorValue[Red4] = 0;
    SensorValue[Red5] = 0;
    int temp = 0;
    int row = 0;
    int rowsWithSquares = 0;
    startPos();
    while (SensorValue[yMax] == 0)
    {
        if (SensorValue[xMin] != 0)
        {
            turnVar = 1;
        }
        if(SensorValue[xMax] != 0)
        {
            turnVar = 2;
        }
        temp = squares;
        switch (turnVar)
        {
        case 1:
            moveRight();
            if (squares > temp)
            {
                rowsWithSquares++;
                array[row] = 1;
            }
            row++;
            break;
        case 2:
            moveLeft();
            if (squares > temp)
            {
                rowsWithSquares++;
                array[row] = 1;
            }
            row++;
            break;
        default:
            break;
        }
        moveUp();
    }
    moveRight();
    bool sameSurface = true;
    startPos();
    wait1Msec(5000);
    if (sameSurface == true)
    {
        scanSameSurface(rowsWithSquares);
    }
}
void moveRight()
{
    while (SensorValue[xMax] == 0)
    {
        motor[xMotor] = speed;
        /*if (SensorValue[IROut] == threshold){
        squares++;
        results(squares);
        }
        */
        if (SensorValue[IROut] > threshold)
        {
            // clearTimer(T2);
            while (SensorValue[IROut] > threshold)
            {
                SensorValue[Red] = 1;
            }
            S
                ensorValue[Red] = 0;
            wait1Msec(3000);
            squares = squares + 1;
        }
        results(squares);
    }
    motor[xMotor] = 0;
    wait1Msec(1000);
    turnVar = 0;
}
v
    oid moveLeft()
{
    while (SensorValue[xMin] == 0)
    {
        motor[xMotor] = -speed;
        /*if (SensorValue[IROut] == threshold){
        squares++;
        results(squares);
        }
        */
        if (SensorValue[IROut] > threshold)
        {
            // clearTimer(T2);
            while (SensorValue[IROut] > threshold)
            {
                SensorValue[Red] = 1;
            }
            S
                ensorValue[Red] = 0;
            wait1Msec(3000);
            squares = squares + 1;
        }
        results(squares);
    }
    motor[xMotor] = 0;
    wait1Msec(1000);
    turnVar = 0;
}
void moveUp()
{
    clearTimer(T1);
    while (time1[T1] < 1000)
    {
        motor[yMotor] = speed;
    }
    motor[yMotor] = 0;
    wait1Msec(500);
}
void moveDown()
{
    clearTimer(T1);
    while (time1[T1] < 900)
    {
        motor[yMotor] = -speed;
    }
    motor[yMotor] = 0;
    wait1Msec(500);
}
void startPos()
{
    while (SensorValue[yMin] == 0)
    {
        motor[yMotor] = -speed;
    }
    motor[yMotor] = 0;
    while (SensorValue[xMin] == 0)
    {
        motor[xMotor] = -speed;
    }
    motor[xMotor] = 0;
    motor[yMotor] = 0;
    wait1Msec(1000);
}
void startPos2()
{
    while (SensorValue[yMax] == 0)
    {
        motor[yMotor] = speed;
    }
    motor[yMotor] = 0;
    while (SensorValue[xMin] == 0)
    {
        motor[xMotor] = -speed;
    }
    motor[xMotor] = 0;
    motor[yMotor] = 0;
    wait1Msec(1000);
}
int results(int squares)
{
    if (squares == 1)
    {
        SensorValue[Red1] = 1;
        SensorValue[Red2] = 0;
        SensorValue[Red3] = 0;
        SensorValue[Red4] = 0;
        SensorValue[Red5] = 0;
    }
    if (squares == 2)
    {
        SensorValue[Red1] = 0;
        SensorValue[Red2] = 1;
        SensorValue[Red3] = 0;
        SensorValue[Red4] = 0;
        SensorValue[Red5] = 0;
    }
    if (squares == 3)
    {
        SensorValue[Red1] = 1;
        SensorValue[Red2] = 1;
        SensorValue[Red3] = 0;
        SensorValue[Red4] = 0;
        SensorValue[Red5] = 0;
    }
    if (squares == 4)
    {
        SensorValue[Red1] = 0;
        SensorValue[Red2] = 0;
        SensorValue[Red3] = 1;
        SensorValue[Red4] = 0;
        SensorValue[Red5] = 0;
    }
    if (squares == 5)
    {
        SensorValue[Red1] = 1;
        SensorValue[Red2] = 0;
        SensorValue[Red3] = 1;
        SensorValue[Red4] = 0;
        SensorValue[Red5] = 0;
    }
    if (squares == 6)
    {
        SensorValue[Red1] = 0;
        SensorValue[Red2] = 1;
        SensorValue[Red3] = 1;
        SensorValue[Red4] = 0;
        SensorValue[Red5] = 0;
    }
    i f(squares == 7)
    {
        SensorValue[Red1] = 1;
        SensorValue[Red2] = 1;
        SensorValue[Red3] = 1;
        SensorValue[Red4] = 0;
        SensorValue[Red5] = 0;
    }
    if (squares == 8)
    {
        SensorValue[Red1] = 0;
        SensorValue[Red2] = 0;
        SensorValue[Red3] = 0;
        SensorValue[Red4] = 1;
        SensorValue[Red5] = 0;
    }
    i f(squares == 9)
    {
        SensorValue[Red1] = 1;
        SensorValue[Red2] = 0;
        SensorValue[Red3] = 0;
        SensorValue[Red4] = 1;
        SensorValue[Red5] = 0;
    }
    i f(squares == 10)
    {
        SensorValue[Red1] = 0;
        SensorValue[Red2] = 1;
        SensorValue[Red3] = 0;
        SensorValue[Red4] = 1;
        SensorValue[Red5] = 0;
    }
    if (squares == 11)
    {
        SensorValue[Red1] = 1;
        SensorValue[Red2] = 1;
        SensorValue[Red3] = 0;
        SensorValue[Red4] = 1;
        SensorValue[Red5] = 0;
    }
    if (squares == 12)
    {
        SensorValue[Red1] = 0;
        SensorValue[Red2] = 0;
        SensorValue[Red3] = 1;
        SensorValue[Red4] = 1;
        SensorValue[Red5] = 0;
    }
    if (squares == 13)
    {
        SensorValue[Red1] = 1;
        SensorValue[Red2] = 0;
        SensorValue[Red3] = 1;
        SensorValue[Red4] = 1;
        SensorValue[Red5] = 0;
    }
    if (squares == 14)
    {
        SensorValue[Red1] = 0;
        SensorValue[Red2] = 1;
        SensorValue[Red3] = 1;
        SensorValue[Red4] = 1;
        SensorValue[Red5] = 0;
    }
    if (squares == 15)
    {
        SensorValue[Red1] = 1;
        SensorValue[Red2] = 1;
        SensorValue[Red3] = 1;
        SensorValue[Red4] = 1;
        SensorValue[Red5] = 0;
    }
    if (squares == 16)
    {
        SensorValue[Red1] = 0;
        SensorValue[Red2] = 0;
        SensorValue[Red3] = 0;
        SensorValue[Red4] = 0;
        SensorValue[Red5] = 1;
    }
    return squares;
}
void scanSameSurface(int num)
{
    squares = 0;
    SensorValue[Red] = 0;
    SensorValue[Red1] = 0;
    SensorValue[Red2] = 0;
    SensorValue[Red3] = 0;
    SensorValue[Red4] = 0;
    SensorValue[Red5] = 0;
    int rowNum = 0;
    int switchVar = 0;
    startPos();
    for (int i = 0; i < num; i++)
    {
        if (SensorValue[xMin] != 0)
        {
            switchVar = 1;
        }
        if (SensorValue[xMax] != 0)
        {
            switchVar = 2;
        }
        switch (switchVar)
        {
        case 1:
            moveRight();
            rowNum++;
            break;
        case 2:
            moveLeft();
            rowNum++;
            break;
        default:
            break;
        }
        moveUp();
        if (array[rowNum] == 0)
        {
            moveUp();
            rowNum++;
        }
    }
    moveRight();
    startPos();
}
