#pragma config(Sensor, dgtl4,  buttonToMove,   sensorDigitalIn)
#pragma config(Sensor, dgtl11, buttonToTurn,   sensorDigitalIn)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//
//	Vex Robotics RobotC Program, Test Code 007
//	Milestone 1: Mechanical Test
//
//	Paisley Kerstens, Aleksia Loewen, Arfaz Hussain
//
//

int motorSpeed = 50;														// (UNIT) centimeter, cm

void moveForwardOneMeter() {
	motor[leftMotor] = motorSpeed;
	motor[rightMotor] = motorSpeed+5;							// calibrating with both motor speed, may differ by weight and circumstance, subject to change
	wait1Msec(2000);
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	wait1Msec(1000);
	/* motorSpeed=-15;
	motor[leftMotor] = motorSpeed;
	motor[rightMotor] = motorSpeed-10;
	wait1Msec(3000); */

}

task main () {
	while (1==1) {
		if (SensorValue[buttonToMove] == 0) {
			moveForwardOneMeter();
		}
		else if (SensorValue(buttonToTurn) == 0) {
			motor[leftMotor] = motorSpeed;
			motor[rightMotor] = 0;
		}
		else {
			motor[leftMotor] = 0;
			motor[rightMotor] = 0;
		}
	}
}
