#pragma config(Sensor, dgtl4,  buttonToMove,   sensorDigitalIn)
#pragma config(Sensor, dgtl11, buttonToTurn,   sensorDigitalIn)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//
//	Vex Robotics RobotC Program
//	Milestone 1: Mechanical Test
//
//	Paisley Kerstens, Aleksia Loewen, Arfaz Hussain
//
//

task main () {
	while (1==1) {
		if (SensorValue(buttonToMove) == 0) {
			//while (1==1) {
				motor[leftMotor] = 127;
				motor[rightMotor] = 127;
			//}
		}
		else if (SensorValue(buttonToTurn) == 0) {
			motor[leftMotor] = 127;
			motor[rightMotor] = 0;
		}
		else {
			motor[leftMotor] = 0;
			motor[rightMotor] = 0;
		}
	}
}
