#pragma config(Sensor, in1, infraC, sensorReflection)
#pragma config(Sensor, dgtl1, RedLED, sensorDigitalOut)
#pragma config(Sensor, dgtl4, StopButton, sensorDigitalIn)
#pragma config(Sensor, dgtl5, SonarIn, sensorSONAR_cm)
#pragma config(Sensor, dgtl7, GreenLED, sensorDigitalOut)
#pragma config(Sensor, dgtl9, LimitSwitchR, sensorDigitalIn)
#pragma config(Sensor, dgtl10, LimitSwitchL, sensorDigitalIn)
#pragma config(Sensor, dgtl11, StartButton, sensorDigitalIn)
#pragma config(Motor, port2, upperMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor, port1, rightMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor, port10, leftMotor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// const int thresholdSensorValue = 1000; // My Idea --> if robot finds a value greater than the threshold

const int motorSpeed = 50;
int rightMotorSpeed = motorSpeed; // Motor Speed
int leftMotorSpeed = motorSpeed;
const int thresholdSensorValue = 1000;

//int OFF = 0; // Light Source ON
int ON = 1;  // Light Source OFF
//int timeConstant = 1500;
// bool stopped = false;

void Stop()
{
    motor[leftMotor] = 0;
    motor[rightMotor] = 0;
}
void moveAround()
{
    motor[leftMotor] = rightMotorSpeed;
    motor[rightMotor] = -leftMotorSpeed;
}
void moveTo()
{
    motor[rightMotor] = rightMotorSpeed;
    motor[leftMotor] = leftMotorSpeed;
}
void moveToSlow()
{
    motor[rightMotor] = rightMotorSpeed - 20;
    motor[leftMotor] = leftMotorSpeed - 20;
}
void moveAroundSlowRight()
{
    motor[rightMotor] = -rightMotorSpeed + 20;
    motor[leftMotor] = leftMotorSpeed - 20;
    wait1Msec(100);
}
void moveAroundSlowLeft()
{
    motor[rightMotor] = +rightMotorSpeed - 20;
    motor[leftMotor] = -leftMotorSpeed + 20;
    wait1Msec(100);
}
// void moveAroundSlowRight_OBJ_PLACEMENT()
// {
//     motor[rightMotor] = -rightMotorSpeed + 20;
//     motor[leftMotor] = +leftMotorSpeed - 20;
//     wait1Msec(250);
// }
// void moveBack()
// {
//     motor[rightMotor] = -rightMotorSpeed;
//     motor[leftMotor] = -leftMotorSpeed;
// }
void moveBack60()
{
    motor[rightMotor] = -rightMotorSpeed;
    motor[leftMotor] = -leftMotorSpeed;
    wait1Msec(1000);
    Stop();
}
void objectPlacement()
{
    /*MAIN*/
    motor[upperMotor] = -15;
    wait1Msec(1500);
    motor[upperMotor] = 0;
}
void objectPlacementReverse()
{
    /*MAIN*/
    motor[upperMotor] = 15;
    wait1Msec(1500);
    motor[upperMotor] = 0;
}
int min(int a, int b)
{
    if (a < b)
    {
        return a;
    }
    else
    {
        return b;
    }
}

int smallestSignal (int SignalOne, int SignalTwo, int SignalThree, int SignalFour, int SignalFive, int SignalSix, int SignalSeven, int SignalEight, int SignalNine, int SignalTen)
{
    int smallest = SignalOne;

    if (SignalTwo < smallest)
    {
        smallest = SignalTwo;
    }

    if (SignalThree < smallest)
    {
        smallest = SignalThree;
    }

    if (SignalFour < smallest)
    {
        smallest = SignalFour;
    }

    if (SignalFive < smallest)
    {
        smallest = SignalFive;
    }

    if (SignalSix < smallest)
    {
        smallest = SignalSix;
    }

    if (SignalSeven < smallest)
    {
        smallest = SignalSeven;
    }

    if (SignalEight < smallest)
    {
        smallest = SignalEight;
    }

    if (SignalNine < smallest)
    {
        smallest = SignalNine;
    }

    if (SignalTen < smallest)
    {
        smallest = SignalNine;
    }

    return smallest;
}

void signalCheck()
{
    while (1 == 1) // re-align
    {
        // take signal 0
        int sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        int sensorValue2 = SensorValue[infraC];
        int signalMain = min(sensorValue1, sensorValue2);

        // take signal -1
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightOne = min(sensorValue1, sensorValue2);

        // take signal -2
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightTwo = min(sensorValue1, sensorValue2);

        // take signal -3
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightThree = min(sensorValue1, sensorValue2);

        // take signal -4
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightFour = min(sensorValue1, sensorValue2);

        
        // take signal -5
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightFive = min(sensorValue1, sensorValue2);


        // take signal -6
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightSix = min(sensorValue1, sensorValue2);

        // take signal -7
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightSeven = min(sensorValue1, sensorValue2);

        // take signal -8
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightEight = min(sensorValue1, sensorValue2);

        // take signal -9
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightNine = min(sensorValue1, sensorValue2);

        // take signal -10
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightTen = min(sensorValue1, sensorValue2);

        // take signal -11
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightEleven = min(sensorValue1, sensorValue2);

        // take signal -12
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightTwelve = min(sensorValue1, sensorValue2);

        // take signal -13
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightThirteen = min(sensorValue1, sensorValue2);

        // take signal -14
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightFourteen = min(sensorValue1, sensorValue2);

        // take signal -15
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightFiveteen = min(sensorValue1, sensorValue2);

        // take signal -16
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightSixteen = min(sensorValue1, sensorValue2);

        // take signal -17
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightSeventeen = min(sensorValue1, sensorValue2);

        // take signal -18
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightEighteen = min(sensorValue1, sensorValue2);

        // take signal -19
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightNineteen = min(sensorValue1, sensorValue2);

        // take signal -20
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightTwenty = min(sensorValue1, sensorValue2);

        // take signal 1
        int countBack = 21;
        while (countBack!=0) 
        {
            moveAroundSlowLeft();
            countBack--;
        }
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftOne = min(sensorValue1, sensorValue2);

        // take signal 2
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftTwo = min(sensorValue1, sensorValue2);

        // take signal 3
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftThree = min(sensorValue1, sensorValue2);

        // take signal 4
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftFour = min(sensorValue1, sensorValue2);

        // take signal 5
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftFive = min(sensorValue1, sensorValue2);

        // take signal 6
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftSix = min(sensorValue1, sensorValue2);

        // take signal 7
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftSeven = min(sensorValue1, sensorValue2);

        // take signal 8
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftEight = min(sensorValue1, sensorValue2);

        // take signal 9
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftNine = min(sensorValue1, sensorValue2);

        // take signal 10
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftTen = min(sensorValue1, sensorValue2);

        // take signal 11
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftEleven = min(sensorValue1, sensorValue2);

        // take signal 12
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftTwelve = min(sensorValue1, sensorValue2);

        // take signal 13
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftThirteen = min(sensorValue1, sensorValue2);

        // take signal 14
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftFourteen = min(sensorValue1, sensorValue2);

        // take signal 15
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftFifteen = min(sensorValue1, sensorValue2);

        // take signal 16
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftSixteen = min(sensorValue1, sensorValue2);

        // take signal 17
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftSeventeen = min(sensorValue1, sensorValue2);

        // take signal 18
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftEighteen = min(sensorValue1, sensorValue2);

        // take signal 19
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftNineteen = min(sensorValue1, sensorValue2);

        // take signal 20
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftTwenty = min(sensorValue1, sensorValue2);

        // now move to 0
        countBack = 20;
        while (countBack != 0)
        {
            moveAroundSlowRight();
            countBack--;
        }

        // calculate the smallest signal
        int signal = smallestSignal2(signalMain, signalRightOne, signalRightTwo, signalRightThree, signalRightFour, signalLeftOne, signalLeftTwo, signalLeftThree, signalLeftFour);
        if (signal == signalRightOne)
        {
            moveAroundSlowRight();
            break;
        }
        if (signal == signalRightTwo)
        {
            moveAroundSlowRight();
            moveAroundSlowRight();
            break;
        }
        if (signal == signalRightThree)
        {
            moveAroundSlowRight();
            moveAroundSlowRight();
            moveAroundSlowRight();
            break;
        }
        if (signal == signalRightFour)
        {
            moveAroundSlowRight();
            moveAroundSlowRight();
            moveAroundSlowRight();
            moveAroundSlowRight();
            break;
        }
        if (signal == signalLeftOne)
        {
            moveAroundSlowLeft();
            break;
        }
        if (signal == signalLeftTwo)
        {
            moveAroundSlowLeft();
            moveAroundSlowLeft();
            break;
        }
        if (signal == signalLeftThree)
        {
            moveAroundSlowLeft();
            moveAroundSlowLeft();
            moveAroundSlowLeft();
            break;
        }
        if (signal == signalLeftFour)
        {
            moveAroundSlowLeft();
            moveAroundSlowLeft();
            moveAroundSlowLeft();
            moveAroundSlowLeft();
            break;
        }
        if (signal == signalMain)
        {
            break;
        }
    }
    return;
}

void signalCheck9()
{
    while (1 == 1) // re-align
    {
        // take signal 0
        int sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        int sensorValue2 = SensorValue[infraC];
        int signalMain = min(sensorValue1, sensorValue2);

        // take signal -1
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightOne = min(sensorValue1, sensorValue2);

        // take signal -2
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightTwo = min(sensorValue1, sensorValue2);

        // take signal -3
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightThree = min(sensorValue1, sensorValue2);

        // take signal -4
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightFour = min(sensorValue1, sensorValue2);

        // take signal 1
        moveAroundSlowLeft();
        moveAroundSlowLeft();
        moveAroundSlowLeft();
        moveAroundSlowLeft();
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftOne = min(sensorValue1, sensorValue2);

        // take signal 2
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftTwo = min(sensorValue1, sensorValue2);

        // take signal 3
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftThree = min(sensorValue1, sensorValue2);

        // take signal 4
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftFour = min(sensorValue1, sensorValue2);

        // now move to 0
        moveAroundSlowRight();
        moveAroundSlowRight();
        moveAroundSlowRight();
        moveAroundSlowRight();

        // calculate the smallest signal
        int signal = smallestSignal2(signalMain, signalRightOne, signalRightTwo, signalRightThree, signalRightFour, signalLeftOne, signalLeftTwo, signalLeftThree, signalLeftFour);
        if (signal == signalRightOne)
        {
            moveAroundSlowRight();
            break;
        }
        if (signal == signalRightTwo)
        {
            moveAroundSlowRight();
            moveAroundSlowRight();
            break;
        }
        if (signal == signalRightThree)
        {
            moveAroundSlowRight();
            moveAroundSlowRight();
            moveAroundSlowRight();
            break;
        }
        if (signal == signalRightFour)
        {
            moveAroundSlowRight();
            moveAroundSlowRight();
            moveAroundSlowRight();
            moveAroundSlowRight();
            break;
        }
        if (signal == signalLeftOne)
        {
            moveAroundSlowLeft();
            break;
        }
        if (signal == signalLeftTwo)
        {
            moveAroundSlowLeft();
            moveAroundSlowLeft();
            break;
        }
        if (signal == signalLeftThree)
        {
            moveAroundSlowLeft();
            moveAroundSlowLeft();
            moveAroundSlowLeft();
            break;
        }
        if (signal == signalLeftFour)
        {
            moveAroundSlowLeft();
            moveAroundSlowLeft();
            moveAroundSlowLeft();
            moveAroundSlowLeft();
            break;
        }
        if (signal == signalMain)
        {
            break;
        }
    }
    return;
}

task main()
{
    int sensorValue1 = 0;
    int sensorValue2 = 0;
    while (1 == 1)
    {
        if (SensorValue[StartButton] == 0)
        {
            while (1 == 1) // spin around find target
            {
                moveAround();
                int sensorValue1 = 0;
                int sensorValue2 = 0;
                sensorValue1 = SensorValue[infraC];
                wait1Msec(51);
                sensorValue2 = SensorValue[infraC];
                int signal = min(sensorValue1, sensorValue2);
                if (signal < thresholdSensorValue)
                {
                    // SensorValue(RedLED) = ON;
                    Stop();
                    wait1Msec(1000); // test
                    break;
                }
            }
            // move to target till off path
            while ((((SensorValue[SonarIn] > 80) && (SensorValue[SonarIn] != -1))))
            {
                moveTo();
            }
            Stop();
            wait1Msec(1000);
            signalCheck5();
            // move to target till off path
            while ((SensorValue[SonarIn] > 50) && (SensorValue[SonarIn] != -1))
            {
                moveTo();
            }
            Stop();
            wait1Msec(1000);
            signalCheck9();
            while (1 == 1) // go to target
            {
                moveToSlow();
                int sensorValue1 = SensorValue[SonarIn];
                if ((sensorValue1 <= 3) && (sensorValue1 != -1))
                {
                    Stop();
                    break;
                }
            }
            //moveAroundSlowRight_OBJ_PLACEMENT();
            objectPlacement();
            objectPlacementReverse();
            Stop();
            wait1Msec(500);
            moveBack60();
            Stop();
            SensorValue(RedLED) = ON;
        }
    }
}
