#pragma config(Sensor, in1, infraC, sensorReflection)
#pragma config(Sensor, dgtl1, RedLED, sensorDigitalOut)
#pragma config(Sensor, dgtl4, StopButton, sensorDigitalIn)
#pragma config(Sensor, dgtl5, SonarIn, sensorSONAR_cm)
#pragma config(Sensor, dgtl7, GreenLED, sensorDigitalOut)
#pragma config(Sensor, dgtl9, LimitSwitchR, sensorDigitalIn)
#pragma config(Sensor, dgtl10, LimitSwitchL, sensorDigitalIn)
#pragma config(Sensor, dgtl11, StartButton, sensorDigitalIn)
#pragma config(Motor, port2, upperMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor, port1, rightMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor, port10, leftMotor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int motorSpeed = 50;
int rightMotorSpeed = motorSpeed;
int leftMotorSpeed = motorSpeed;
const int thresholdSensorValue = 1000;

int ON = 1;

void Stop()
{
    motor[leftMotor] = 0;
    motor[rightMotor] = 0;
}
void moveAround()
{
    motor[leftMotor] = rightMotorSpeed;
    motor[rightMotor] = -leftMotorSpeed;
}
void moveTo()
{
    motor[rightMotor] = rightMotorSpeed;
    motor[leftMotor] = leftMotorSpeed;
}
void moveToSlow()
{
    motor[rightMotor] = rightMotorSpeed - 20;
    motor[leftMotor] = leftMotorSpeed - 20;
}
void moveAroundSlowRight()
{
    motor[rightMotor] = -rightMotorSpeed + 20;
    motor[leftMotor] = leftMotorSpeed - 20;
    wait1Msec(200);
    Stop();
}
void moveAroundSlowLeft()
{
    motor[rightMotor] = +rightMotorSpeed - 20;
    motor[leftMotor] = -leftMotorSpeed + 20;
    wait1Msec(200);
    Stop();
}
void moveBack60()
{
    motor[rightMotor] = -rightMotorSpeed;
    motor[leftMotor] = -leftMotorSpeed;
    wait1Msec(1000);
    Stop();
}
void objectPlacement()
{
    /*MAIN*/
    motor[upperMotor] = -15;
    wait1Msec(4000);
    motor[upperMotor] = 0;
    wait1Msec(5000);
}
void objectPlacementReverse()
{
    /*MAIN*/
    motor[upperMotor] = 15;
    wait1Msec(2000);
    motor[upperMotor] = 0;
}
int min(int a, int b)
{
    if (a < b)
    {
        return a;
    }
    else
    {
        return b;
    }
}

int smallestSignal10(int SignalOne, int SignalTwo, int SignalThree, int SignalFour, int SignalFive, int SignalSix, int SignalSeven, int SignalEight, int SignalNine, int SignalTen)
{
    int smallest = SignalOne;
    if (SignalTwo < smallest) { smallest = SignalTwo;}
    if (SignalThree < smallest) {smallest = SignalThree;}
    if (SignalFour < smallest) {smallest = SignalFour;}
    if (SignalFive < smallest) {smallest = SignalFive;}
    if (SignalSix < smallest) {smallest = SignalSix;}
    if (SignalSeven < smallest) {smallest = SignalSeven;}
    if (SignalEight < smallest) {smallest = SignalEight;}
    if (SignalNine < smallest) {smallest = SignalNine;}
    if (SignalTen < smallest) {smallest = SignalNine;}
    return smallest;
}

int smallestSignal5(int SignalOne, int SignalTwo, int SignalThree, int SignalFour, int SignalFive)
{
    int smallest = SignalOne;
    if (SignalTwo < smallest) {smallest = SignalTwo;}
    if (SignalThree < smallest) {smallest = SignalThree;}
    if (SignalFour < smallest) {smallest = SignalFour;}
    if (SignalFive < smallest) {smallest = SignalFive;}

    return smallest;
}

void signalCheck()
{
    while (1 == 1) // re-align
    {
        // take signal 0
        int sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        int sensorValue2 = SensorValue[infraC];
        int signalMain = min(sensorValue1, sensorValue2);

        // take signal -1
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightOne = min(sensorValue1, sensorValue2);

        // take signal -2
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightTwo = min(sensorValue1, sensorValue2);

        // take signal -3
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightThree = min(sensorValue1, sensorValue2);

        // take signal -4
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightFour = min(sensorValue1, sensorValue2);

        // take signal -5
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightFive = min(sensorValue1, sensorValue2);

        // take signal -6
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightSix = min(sensorValue1, sensorValue2);

        // take signal -7
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightSeven = min(sensorValue1, sensorValue2);

        // take signal -8
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightEight = min(sensorValue1, sensorValue2);

        // take signal -9
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightNine = min(sensorValue1, sensorValue2);

        // take signal -10
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightTen = min(sensorValue1, sensorValue2);

        // take signal -11
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightEleven = min(sensorValue1, sensorValue2);

        // take signal -12
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightTwelve = min(sensorValue1, sensorValue2);

        // take signal -13
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightThirteen = min(sensorValue1, sensorValue2);

        // take signal -14
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightFourteen = min(sensorValue1, sensorValue2);

        // take signal -15
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightFifteen = min(sensorValue1, sensorValue2);

        // take signal -16
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightSixteen = min(sensorValue1, sensorValue2);

        // take signal -17
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightSeventeen = min(sensorValue1, sensorValue2);

        // take signal -18
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightEighteen = min(sensorValue1, sensorValue2);

        // take signal -19
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightNineteen = min(sensorValue1, sensorValue2);

        // take signal -20
        moveAroundSlowRight();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalRightTwenty = min(sensorValue1, sensorValue2);

        // take signal 1
        int countBack = -20;
        while (countBack != 1)
        {
            moveAroundSlowLeft();
            countBack++;
        }
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftOne = min(sensorValue1, sensorValue2);

        // take signal 2
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftTwo = min(sensorValue1, sensorValue2);

        // take signal 3
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftThree = min(sensorValue1, sensorValue2);

        // take signal 4
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftFour = min(sensorValue1, sensorValue2);

        // take signal 5
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftFive = min(sensorValue1, sensorValue2);

        // take signal 6
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftSix = min(sensorValue1, sensorValue2);

        // take signal 7
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftSeven = min(sensorValue1, sensorValue2);

        // take signal 8
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftEight = min(sensorValue1, sensorValue2);

        // take signal 9
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftNine = min(sensorValue1, sensorValue2);

        // take signal 10
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftTen = min(sensorValue1, sensorValue2);

        // take signal 11
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftEleven = min(sensorValue1, sensorValue2);

        // take signal 12
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftTwelve = min(sensorValue1, sensorValue2);

        // take signal 13
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftThirteen = min(sensorValue1, sensorValue2);

        // take signal 14
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftFourteen = min(sensorValue1, sensorValue2);

        // take signal 15
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftFifteen = min(sensorValue1, sensorValue2);

        // take signal 16
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftSixteen = min(sensorValue1, sensorValue2);

        // take signal 17
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftSeventeen = min(sensorValue1, sensorValue2);

        // take signal 18
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftEighteen = min(sensorValue1, sensorValue2);

        // take signal 19
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftNineteen = min(sensorValue1, sensorValue2);

        // take signal 20
        moveAroundSlowLeft();
        sensorValue1 = SensorValue[infraC];
        wait1Msec(51);
        sensorValue2 = SensorValue[infraC];
        int signalLeftTwenty = min(sensorValue1, sensorValue2);

        // now move to 0
        countBack = 20;
        while (countBack != 0)
        {
            moveAroundSlowRight();
            countBack--;
        }

        // calculate the smallest signal
        int signal1 = smallestSignal10(signalRightOne, signalRightTwo, signalRightThree, signalRightFour, signalRightFive, signalRightSix, signalRightSeven, signalRightEight, signalRightNine, signalRightTen);
        int signal2 = smallestSignal10(signalLeftOne, signalLeftTwo, signalLeftThree, signalLeftFour, signalLeftFive, signalLeftSix, signalLeftSeven, signalLeftEight, signalLeftNine, signalLeftTen);
        int signal3 = smallestSignal10(signalRightEleven, signalRightTwelve, signalRightThirteen, signalRightFourteen, signalRightFifteen, signalRightSixteen, signalRightSeventeen, signalRightEighteen, signalRightNineteen, signalRightTwenty);
        int signal4 = smallestSignal10(signalLeftEleven, signalLeftTwelve, signalLeftThirteen, signalLeftFourteen, signalLeftFifteen, signalLeftSixteen, signalLeftSeventeen, signalLeftEighteen, signalLeftNineteen, signalLeftTwenty);
        int signal5 = signalMain;
        int signal = smallestSignal5(signal1, signal2, signal3, signal4, signal5);

        if (signal == signalRightOne)
        {
            moveAroundSlowRight();
            break;
        }
        if (signal == signalRightTwo)
        {
            moveAroundSlowRight();
            moveAroundSlowRight();
            break;
        }
        if (signal == signalRightThree)
        {
            moveAroundSlowRight();
            moveAroundSlowRight();
            moveAroundSlowRight();
            break;
        }
        if (signal == signalRightFour)
        {
            moveAroundSlowRight();
            moveAroundSlowRight();
            moveAroundSlowRight();
            moveAroundSlowRight();
            break;
        }
        if (signal == signalRightFive)
        {
            countBack = 0;
            while (countBack != 5)
            {
                moveAroundSlowRight();
                countBack++;
            }
            break;
        }
        if (signal == signalRightSix)
        {
            countBack = 0;
            while (countBack != 6)
            {
                moveAroundSlowRight();
                countBack++;
            }
            break;
        }
        if (signal == signalRightSeven)
        {
            countBack = 0;
            while (countBack != 7)
            {
                moveAroundSlowRight();
                countBack++;
            }
            break;
        }
        if (signal == signalRightEight)
        {
            countBack = 0;
            while (countBack != 8)
            {
                moveAroundSlowRight();
                countBack++;
            }
            break;
        }
        if (signal == signalRightNine)
        {
            countBack = 0;
            while (countBack != 9)
            {
                moveAroundSlowRight();
                countBack++;
            }
            break;
        }
        if (signal == signalRightTen)
        {
            countBack = 0;
            while (countBack != 10)
            {
                moveAroundSlowRight();
                countBack++;
            }
            break;
        }
        if (signal == signalRightEleven)
        {
            countBack = 0;
            while (countBack != 11)
            {
                moveAroundSlowRight();
                countBack++;
            }
            break;
        }
        if (signal == signalRightTwelve)
        {
            countBack = 0;
            while (countBack != 12)
            {
                moveAroundSlowRight();
                countBack++;
            }
            break;
        }
        if (signal == signalRightThirteen)
        {
            countBack = 0;
            while (countBack != 13)
            {
                moveAroundSlowRight();
                countBack++;
            }
            break;
        }
        if (signal == signalRightFourteen)
        {
            countBack = 0;
            while (countBack != 14)
            {
                moveAroundSlowRight();
                countBack++;
            }
            break;
        }
        if (signal == signalRightFifteen)
        {
            countBack = 0;
            while (countBack != 15)
            {
                moveAroundSlowRight();
                countBack++;
            }
            break;
        }
        if (signal == signalRightSixteen)
        {
            countBack = 0;
            while (countBack != 16)
            {
                moveAroundSlowRight();
                countBack++;
            }
            break;
        }
        if (signal == signalRightSeventeen)
        {
            countBack = 0;
            while (countBack != 17)
            {
                moveAroundSlowRight();
                countBack++;
            }
            break;
        }
        if (signal == signalRightEighteen)
        {
            countBack = 0;
            while (countBack != 18)
            {
                moveAroundSlowRight();
                countBack++;
            }
            break;
        }
        if (signal == signalRightNineteen)
        {
            countBack = 0;
            while (countBack != 19)
            {
                moveAroundSlowRight();
                countBack++;
            }
            break;
        }
        if (signal == signalRightTwenty)
        {
            countBack = 0;
            while (countBack != 20)
            {
                moveAroundSlowRight();
                countBack++;
            }
            break;
        }
        if (signal == signalLeftOne)
        {
            moveAroundSlowLeft();
            break;
        }
        if (signal == signalLeftTwo)
        {
            moveAroundSlowLeft();
            moveAroundSlowLeft();
            break;
        }
        if (signal == signalLeftThree)
        {
            moveAroundSlowLeft();
            moveAroundSlowLeft();
            moveAroundSlowLeft();
            break;
        }
        if (signal == signalLeftFour)
        {
            moveAroundSlowLeft();
            moveAroundSlowLeft();
            moveAroundSlowLeft();
            moveAroundSlowLeft();
            break;
        }
        if (signal == signalLeftFive)
        {
            countBack = 0;
            while (countBack != 5)
            {
                moveAroundSlowLeft();
                countBack++;
            }
            break;
        }
        if (signal == signalLeftSix)
        {
            countBack = 0;
            while (countBack != 6)
            {
                moveAroundSlowLeft();
                countBack++;
            }
            break;
        }
        if (signal == signalLeftSeven)
        {
            countBack = 0;
            while (countBack != 7)
            {
                moveAroundSlowLeft();
                countBack++;
            }
            break;
        }
        if (signal == signalLeftEight)
        {
            countBack = 0;
            while (countBack != 8)
            {
                moveAroundSlowLeft();
                countBack++;
            }
            break;
        }
        if (signal == signalLeftNine)
        {
            countBack = 0;
            while (countBack != 9)
            {
                moveAroundSlowLeft();
                countBack++;
            }
            break;
        }
        if (signal == signalLeftTen)
        {
            countBack = 0;
            while (countBack != 10)
            {
                moveAroundSlowLeft();
                countBack++;
            }
            break;
        }
        if (signal == signalLeftEleven)
        {
            countBack = 0;
            while (countBack != 11)
            {
                moveAroundSlowLeft();
                countBack++;
            }
            break;
        }
        if (signal == signalLeftTwelve)
        {
            countBack = 0;
            while (countBack != 12)
            {
                moveAroundSlowLeft();
                countBack++;
            }
            break;
        }
        if (signal == signalLeftThirteen)
        {
            countBack = 0;
            while (countBack != 13)
            {
                moveAroundSlowLeft();
                countBack++;
            }
            break;
        }
        if (signal == signalLeftFourteen)
        {
            countBack = 0;
            while (countBack != 14)
            {
                moveAroundSlowLeft();
                countBack++;
            }
            break;
        }
        if (signal == signalLeftFifteen)
        {
            countBack = 0;
            while (countBack != 15)
            {
                moveAroundSlowLeft();
                countBack++;
            }
            break;
        }
        if (signal == signalLeftSixteen)
        {
            countBack = 0;
            while (countBack != 16)
            {
                moveAroundSlowLeft();
                countBack++;
            }
            break;
        }
        if (signal == signalLeftSeventeen)
        {
            countBack = 0;
            while (countBack != 17)
            {
                moveAroundSlowLeft();
                countBack++;
            }
            break;
        }
        if (signal == signalLeftEighteen)
        {
            countBack = 0;
            while (countBack != 18)
            {
                moveAroundSlowLeft();
                countBack++;
            }
            break;
        }
        if (signal == signalLeftNineteen)
        {
            countBack = 0;
            while (countBack != 19)
            {
                moveAroundSlowLeft();
                countBack++;
            }
            break;
        }
        if (signal == signalLeftTwenty)
        {
            countBack = 0;
            while (countBack != 20)
            {
                moveAroundSlowLeft();
                countBack++;
            }
            break;
        }
        if (signal == signalMain)
        {
            break;
        }
    }
    return;
}

task main()
{
    int sensorValue1 = 0;
    int sensorValue2 = 0;
    while (1 == 1)
    {
        if (SensorValue[StartButton] == 0)
        {
            while (1 == 1) // spin around find target
            {
                moveAround();
                int sensorValue1 = 0;
                int sensorValue2 = 0;
                sensorValue1 = SensorValue[infraC];
                wait1Msec(51);
                sensorValue2 = SensorValue[infraC];
                int signal = min(sensorValue1, sensorValue2);
                if (signal < thresholdSensorValue)
                {
                    SensorValue(RedLED) = ON;
                    Stop();
                    wait1Msec(1000); // test
                    break;
                }
            }
            // move to target till off path
            while ((((SensorValue[SonarIn] > 80) && (SensorValue[SonarIn] != -1))))
            {
                moveTo();
            }
            Stop();
            wait1Msec(1000);
            signalCheck();
            // move to target till off path
            while ((SensorValue[SonarIn] > 30) && (SensorValue[SonarIn] != -1))
            {
                moveTo();
            }
            Stop();
            wait1Msec(1000);
            signalCheck();
            while (1 == 1) // go to target
            {
                moveToSlow();
                int sensorValue1 = SensorValue[SonarIn];
                if ((sensorValue1 <= 3) && (sensorValue1 != -1))
                {
                    Stop();
                    break;
                }
            }
            objectPlacement();
            objectPlacementReverse();
            Stop();
            wait1Msec(500);
            moveBack60();
            Stop();
            SensorValue(RedLED) = ON;
        }
    }
}
