#pragma config(Sensor, in1, infraC, sensorReflection)
#pragma config(Sensor, dgtl1, RedLED, sensorDigitalOut)
#pragma config(Sensor, dgtl4, StartButton, sensorDigitalIn)
#pragma config(Sensor, dgtl5, SonarIn, sensorSONAR_cm)
#pragma config(Sensor, dgtl7, GreenLED, sensorDigitalOut)
#pragma config(Sensor, dgtl11, StopButton, sensorDigitalIn)
#pragma config(Motor, port1, rightMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor, port10, leftMotor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int thresholdSensorValue = 1000; // My Idea --> if robot finds a value greater than the threshold

const int motorSpeed = 50;
int rightMotorSpeed = motorSpeed; // Motor Speed
int leftMotorSpeed = motorSpeed + 5;

int OFF = 0; // Light Source ON
int ON = 1;  // Light Source OFF

// bool stopped = false;
void DistanceDetection()
{
	while (1 == 1)
	{
		SensorValue(RedLED) = ON;
		wait1Msec(1000);
		SensorValue(RedLED) = OFF;
		wait1Msec(1000);
		SensorValue(RedLED) = ON;
		wait1Msec(1000);
		SensorValue(RedLED) = OFF;
		wait1Msec(1000);
		if (SensorValue[StartButton] == 0)
		{
			break;
		}
	}
	return;
}
void Stop()
{
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}
void moveAround()
{
	motor[leftMotor] = rightMotorSpeed;
	motor[rightMotor] = leftMotorSpeed;
}
task main()
{
	while (1 == 1)
	{
		//SensorValue(RedLED) = OFF;
		//SensorValue(GreenLED) = ON;
		if (SensorValue[StartButton] == 0)
		{
			SensorValue(RedLED) = OFF ;
			int sensorValue1 = 0;
			int sensorValue2 = 0;
			while (1 == 1)
			{
				sensorValue1 = SensorValue[infraC];
				wait1Msec(50);
				sensorValue2 = SensorValue[infraC];
				if ((sensorValue1< thresholdSensorValue)||(sensorValue2< thresholdSensorValue))
				{
					SensorValue(RedLED) = ON;
				}
				else
				{
					SensorValue(RedLED) = OFF;
				}
				while ((sensorValue1 < 100)||(sensorValue2 < 100))
				{
					SensorValue(RedLED) = ON;
					wait1Msec(500);
					SensorValue(RedLED) = OFF;
					wait1Msec(500);
					//SensorValue(RedLED) = ON;
					//wait1Msec(500);
					//SensorValue(RedLED) = OFF;
					//wait1Msec(500);
					//DistanceDetection();
					//break;
				sensorValue1 = SensorValue[infraC];
				wait1Msec(50);
				sensorValue2 = SensorValue[infraC];
				}
			}
		}
	}
}
