#pragma config(Sensor, dgtl4,  buttonToMove,   sensorDigitalIn)
#pragma config(Sensor, dgtl6,  SonarIn,        sensorSONAR_cm)
#pragma config(Sensor, dgtl11, buttonToTurn,   sensorDigitalIn)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*************************************************************************
 *
 *
 * Electrical Test 01: IR Sensor Test
 *
 * Breadboard Connected To: Digital Port 1 (LED Light Signal)
 *                          Analog Port 7 (PhotoTransistor)
 *
 *
 *************************************************************************/

// Threshold of value read from phototransistor circuit.
//const int IR_SENSOR_THRESHOLD = 1000;

//int motorSpeed = 25;

/*
void SourceDetectionSignal ()
{
    SensorValue(RedLED) = OFF;
    wait1Msec(1000);
    SensorValue(RedLED) = ON;
    wait1Msec(1000);
    SensorValue(RedLED) = OFF;
    wait1Msec(1000);
    SensorValue(RedLED) = ON;
    wait1Msec(1000);
    SensorValue(RedLED) = OFF;
}
*/

task main() {
    while (1==1) {
        motor[leftMotor] = 0;
        motor[rightMotor] = 0;
    }
}
