#pragma config(Motor, port1, leftMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor, port10, rightMotor, tmotorVex393_HBridge, openLoop)
#pragma config(Sensor, in1, InfraCollector, sensorReflection)
#pragma config(Sensor, dgtl1, RedLED, sensorDigitalOut)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*************************************************************************

Description: This program turns on an LED when the phototransistor is
exposed to a sufficiently large amount of infrared light.

*************************************************************************/

/*************************************************************************
 *
 *
 * Electrical Test 01: IR Sensor Test
 *
 * Breadboard Connected To: Digital Port 1 (LED Light Signal)
 *                          Analog Port 7 (PhotoTransistor)
 *
 *
 *************************************************************************/

// Threshold of value read from phototransistor circuit.
const int IR_SENSOR_THRESHOLD = 1000;

enum programState
{
  LookingForSignal = 0,
  FoundSignal = 1
};

const int motorSpeed = 50;
const int OFF = 0;                // Light Source ON
const int ON = 1;                 // Light Source OFF

void SourceDetectionSignal ()
{
    SensorValue(RedLED) = OFF;
    wait1Msec(500);
    SensorValue(RedLED) = ON;
    wait1Msec(500);
    SensorValue(RedLED) = OFF;
    wait1Msec(500);
    SensorValue(RedLED) = ON;
    wait1Msec(500);
    SensorValue(RedLED) = OFF;
}

void moveStraight()
{
    motor[leftMotor] = motorSpeed;
    motor[rightMotor] = motorSpeed + 5;
    wait1Msec(2500);
}

void turnRight()
{
    motor[leftMotor] = motorSpeed;
    motor[rightMotor] = 0;
    wait1Msec(1700);
}

task main() {
    programState currState = LookingForSignal;
    SourceDetectionSignal();

    while (1==1) {
        switch (currState) {
            case (LookingForSignal):
                SensorValue(RedLED) = OFF;

                /* When an infrared beam from the IR LED
                 * hits the phototransistor, the InfraCollector port
                 * should go above the IR_SENSOR_THRESHOLD value.
                 */
                if (SensorValue[InfraCollector] < IR_SENSOR_THRESHOLD) {currState = FoundSignal;}
                break;
            case (FoundSignal):
                SensorValue(RedLED) = ON;
                /*     When the infrared beam from the IR LED 
                 *     to the phototransistor is blocked, 
                 *     the InfraCollector port should go below 
                 *     the IR_SENSOR_THRESHOLD value.
                 */
                if (SensorValue(InfraCollector) > IR_SENSOR_THRESHOLD) {currState = MovingToTarget;}
                break;

            default: // We should never be in this state.
        }
    }
}
