#pragma config(Sensor, in1,    infraC,         sensorReflection)
#pragma config(Sensor, in2,    InfraC2,        sensorAnalog)
#pragma config(Sensor, dgtl1,  RedLED,         sensorDigitalOut)
#pragma config(Sensor, dgtl4,  buttonToMove,   sensorDigitalIn)
#pragma config(Sensor, dgtl6,  SonarIn,        sensorSONAR_cm)
#pragma config(Sensor, dgtl11, buttonToTurn,   sensorDigitalIn)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*************************************************************************
 *
 *
 * Electrical Test 01: IR Sensor Test
 *
 * Breadboard Connected To: Digital Port 1 (LED Light Signal)
 *                          Analog Port 7 (PhotoTransistor)
 *
 *
 *************************************************************************/

task main() {
    //SourceDetectionSignal();
    while (1==1) {
        if (SensorValue[buttonToMove] == 0)
        {
            while (1 == 1)
            {
                motor[leftMotor] = 15;
                motor[rightMotor] = 15;
                if (SensorValue[buttonToTurn] == 0) {
                    motor[leftMotor] = 0;
                    motor[rightMotor] = 0;
                    break;
                }
            
            }
        }
    }
}
